#pragma region LICENSE

// MIT License
//
// Copyright (c) 2025 Rohan Bharatia
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

#pragma endregion LICENSE

#pragma once

#ifndef _CORE_CODES_H_
    #define _CORE_CODES_H_

#include "PCH.h"

namespace Nt
{
    enum class NT_API Keycode
    {
        KeyCodeNone        = SDLK_UNKNOWN,
        Return             = SDLK_RETURN,
        Escape             = SDLK_ESCAPE,
        Backspace          = SDLK_BACKSPACE,
        Tab                = SDLK_TAB,
        Space              = SDLK_SPACE,
        Exclaim            = SDLK_EXCLAIM,
        DoubleApostrophe   = SDLK_DBLAPOSTROPHE,
        Hash               = SDLK_HASH,
        Dollar             = SDLK_DOLLAR,
        Percent            = SDLK_PERCENT,
        Ampersand          = SDLK_AMPERSAND,
        Apostrophe         = SDLK_APOSTROPHE,
        LeftParen          = SDLK_LEFTPAREN,
        RightParen         = SDLK_RIGHTPAREN,
        Asterisk           = SDLK_ASTERISK,
        Plus               = SDLK_PLUS,
        Comma              = SDLK_COMMA,
        Minus              = SDLK_MINUS,
        Period             = SDLK_PERIOD,
        Slash              = SDLK_SLASH,
        Num0               = SDLK_0,
        Num1               = SDLK_1,
        Num2               = SDLK_2,
        Num3               = SDLK_3,
        Num4               = SDLK_4,
        Num5               = SDLK_5,
        Num6               = SDLK_6,
        Num7               = SDLK_7,
        Num8               = SDLK_8,
        Num9               = SDLK_9,
        Colon              = SDLK_COLON,
        Semicolon          = SDLK_SEMICOLON,
        Less               = SDLK_LESS,
        Equals             = SDLK_EQUALS,
        Greater            = SDLK_GREATER,
        Question           = SDLK_QUESTION,
        At                 = SDLK_AT,
        LeftBracket        = SDLK_LEFTBRACKET,
        Backslash          = SDLK_BACKSLASH,
        RightBracket       = SDLK_RIGHTBRACKET,
        Caret              = SDLK_CARET,
        Underscore         = SDLK_UNDERSCORE,
        Grave              = SDLK_GRAVE,
        A                  = SDLK_A,
        B                  = SDLK_B,
        C                  = SDLK_C,
        D                  = SDLK_D,
        E                  = SDLK_E,
        F                  = SDLK_F,
        G                  = SDLK_G,
        H                  = SDLK_H,
        I                  = SDLK_I,
        J                  = SDLK_J,
        K                  = SDLK_K,
        L                  = SDLK_L,
        M                  = SDLK_M,
        N                  = SDLK_N,
        O                  = SDLK_O,
        P                  = SDLK_P,
        Q                  = SDLK_Q,
        R                  = SDLK_R,
        S                  = SDLK_S,
        T                  = SDLK_T,
        U                  = SDLK_U,
        V                  = SDLK_V,
        W                  = SDLK_W,
        X                  = SDLK_X,
        Y                  = SDLK_Y,
        Z                  = SDLK_Z,
        LeftBrace          = SDLK_LEFTBRACE,
        Pipe               = SDLK_PIPE,
        RightBrace         = SDLK_RIGHTBRACE,
        Tilde              = SDLK_TILDE,
        Delete             = SDLK_DELETE,
        PlusMinus          = SDLK_PLUSMINUS,
        CapsLock           = SDLK_CAPSLOCK,
        F1                 = SDLK_F1,
        F2                 = SDLK_F2,
        F3                 = SDLK_F3,
        F4                 = SDLK_F4,
        F5                 = SDLK_F5,
        F6                 = SDLK_F6,
        F7                 = SDLK_F7,
        F8                 = SDLK_F8,
        F9                 = SDLK_F9,
        F10                = SDLK_F10,
        F11                = SDLK_F11,
        F12                = SDLK_F12,
        PrintScreen        = SDLK_PRINTSCREEN,
        ScrollLock         = SDLK_SCROLLLOCK,
        Pause              = SDLK_PAUSE,
        Insert             = SDLK_INSERT,
        Home               = SDLK_HOME,
        PageUp             = SDLK_PAGEUP,
        End                = SDLK_END,
        PageDown           = SDLK_PAGEDOWN,
        Right              = SDLK_RIGHT,
        Left               = SDLK_LEFT,
        Down               = SDLK_DOWN,
        Up                 = SDLK_UP,
        NumLockClear       = SDLK_NUMLOCKCLEAR,
        KpDivide           = SDLK_KP_DIVIDE,
        KpMultiply         = SDLK_KP_MULTIPLY,
        KpMinus            = SDLK_KP_MINUS,
        KpPlus             = SDLK_KP_PLUS,
        KpEnter            = SDLK_KP_ENTER,
        Kp1                = SDLK_KP_1,
        Kp2                = SDLK_KP_2,
        Kp3                = SDLK_KP_3,
        Kp4                = SDLK_KP_4,
        Kp5                = SDLK_KP_5,
        Kp6                = SDLK_KP_6,
        Kp7                = SDLK_KP_7,
        Kp8                = SDLK_KP_8,
        Kp9                = SDLK_KP_9,
        Kp0                = SDLK_KP_0,
        KpPeriod           = SDLK_KP_PERIOD,
        Application        = SDLK_APPLICATION,
        Power              = SDLK_POWER,
        KpEquals           = SDLK_KP_EQUALS,
        F13                = SDLK_F13,
        F14                = SDLK_F14,
        F15                = SDLK_F15,
        F16                = SDLK_F16,
        F17                = SDLK_F17,
        F18                = SDLK_F18,
        F19                = SDLK_F19,
        F20                = SDLK_F20,
        F21                = SDLK_F21,
        F22                = SDLK_F22,
        F23                = SDLK_F23,
        F24                = SDLK_F24,
        Execute            = SDLK_EXECUTE,
        Help               = SDLK_HELP,
        Menu               = SDLK_MENU,
        Select             = SDLK_SELECT,
        Stop               = SDLK_STOP,
        Again              = SDLK_AGAIN,
        Undo               = SDLK_UNDO,
        Cut                = SDLK_CUT,
        Copy               = SDLK_COPY,
        Paste              = SDLK_PASTE,
        Find               = SDLK_FIND,
        Mute               = SDLK_MUTE,
        VolumeUp           = SDLK_VOLUMEUP,
        VolumeDown         = SDLK_VOLUMEDOWN,
        KpComma            = SDLK_KP_COMMA,
        KpEqualsAS400      = SDLK_KP_EQUALSAS400,
        AltErase           = SDLK_ALTERASE,
        SysReq             = SDLK_SYSREQ,
        Cancel             = SDLK_CANCEL,
        Clear              = SDLK_CLEAR,
        Prior              = SDLK_PRIOR,
        Return2            = SDLK_RETURN2,
        Separator          = SDLK_SEPARATOR,
        Out                = SDLK_OUT,
        Oper               = SDLK_OPER,
        ClearAgain         = SDLK_CLEARAGAIN,
        CrSel              = SDLK_CRSEL,
        ExSel              = SDLK_EXSEL,
        Kp00               = SDLK_KP_00,
        Kp000              = SDLK_KP_000,
        ThousandsSeparator = SDLK_THOUSANDSSEPARATOR,
        DecimalSeparator   = SDLK_DECIMALSEPARATOR,
        CurrencyUnit       = SDLK_CURRENCYUNIT,
        CurrencySubUnit    = SDLK_CURRENCYSUBUNIT,
        KpLeftParen        = SDLK_KP_LEFTPAREN,
        KpRightParen       = SDLK_KP_RIGHTPAREN,
        KpLeftBrace        = SDLK_KP_LEFTBRACE,
        KpRightBrace       = SDLK_KP_RIGHTBRACE,
        KpTab              = SDLK_KP_TAB,
        KpBackspace        = SDLK_KP_BACKSPACE,
        KpA                = SDLK_KP_A,
        KpB                = SDLK_KP_B,
        KpC                = SDLK_KP_C,
        KpD                = SDLK_KP_D,
        KpE                = SDLK_KP_E,
        KpF                = SDLK_KP_F,
        KpXor              = SDLK_KP_XOR,
        KpPower            = SDLK_KP_POWER,
        KpPercent          = SDLK_KP_PERCENT,
        KpLess             = SDLK_KP_LESS,
        KpGreater          = SDLK_KP_GREATER,
        KpAmpersand        = SDLK_KP_AMPERSAND,
        KpDblAmpersand     = SDLK_KP_DBLAMPERSAND,
        KpVerticalBar      = SDLK_KP_VERTICALBAR,
        KpDblVerticalBar   = SDLK_KP_DBLVERTICALBAR,
        KpColon            = SDLK_KP_COLON,
        KpHash             = SDLK_KP_HASH,
        KpSpace            = SDLK_KP_SPACE,
        KpAt               = SDLK_KP_AT,
        KpExclam           = SDLK_KP_EXCLAM,
        KpMemStore         = SDLK_KP_MEMSTORE,
        KpMemRecall        = SDLK_KP_MEMRECALL,
        KpMemClear         = SDLK_KP_MEMCLEAR,
        KpMemAdd           = SDLK_KP_MEMADD,
        KpMemSubtract      = SDLK_KP_MEMSUBTRACT,
        KpMemMultiply      = SDLK_KP_MEMMULTIPLY,
        KpMemDivide        = SDLK_KP_MEMDIVIDE,
        KpPlusMinus        = SDLK_KP_PLUSMINUS,
        KpClear            = SDLK_KP_CLEAR,
        KpClearEntry       = SDLK_KP_CLEARENTRY,
        KpBinary           = SDLK_KP_BINARY,
        KpOctal            = SDLK_KP_OCTAL,
        KpDecimal          = SDLK_KP_DECIMAL,
        KpHexadecimal      = SDLK_KP_HEXADECIMAL,
        LeftControl        = SDLK_LCTRL,
        LeftShift          = SDLK_LSHIFT,
        LeftAlt            = SDLK_LALT,
        LeftGui            = SDLK_LGUI,
        RightControl       = SDLK_RCTRL,
        RightShift         = SDLK_RSHIFT,
        RightAlt           = SDLK_RALT,
        RightGui           = SDLK_RGUI,
        Mode               = SDLK_MODE,
        Sleep              = SDLK_SLEEP,
        Wake               = SDLK_WAKE,
        ChannelUp          = SDLK_CHANNEL_INCREMENT,
        ChannelDown        = SDLK_CHANNEL_DECREMENT,
        MediaPlay          = SDLK_MEDIA_PLAY,
        MediaPause         = SDLK_MEDIA_PAUSE,
        MediaRecord        = SDLK_MEDIA_RECORD,
        MediaFastForward   = SDLK_MEDIA_FAST_FORWARD,
        MediaRewind        = SDLK_MEDIA_REWIND,
        MediaTrackNext     = SDLK_MEDIA_NEXT_TRACK,
        MediaTrackPrevious = SDLK_MEDIA_PREVIOUS_TRACK,
        MediaStop          = SDLK_MEDIA_STOP,
        MediaEject         = SDLK_MEDIA_EJECT,
        MediaPlayPause     = SDLK_MEDIA_PLAY_PAUSE,
        MediaSelect        = SDLK_MEDIA_SELECT,
        ACNew              = SDLK_AC_NEW,
        ACOpen             = SDLK_AC_OPEN,
        ACClose            = SDLK_AC_CLOSE,
        ACExit             = SDLK_AC_EXIT,
        ACSave             = SDLK_AC_SAVE,
        ACPrint            = SDLK_AC_PRINT,
        ACProperties       = SDLK_AC_PROPERTIES,
        ACSearch           = SDLK_AC_SEARCH,
        ACHome             = SDLK_AC_HOME,
        ACBack             = SDLK_AC_BACK,
        ACForward          = SDLK_AC_FORWARD,
        ACStop             = SDLK_AC_STOP,
        ACRefresh          = SDLK_AC_REFRESH,
        ACBookmarks        = SDLK_AC_BOOKMARKS,
        SoftLeft           = SDLK_SOFTLEFT,
        SoftRight          = SDLK_SOFTRIGHT,
        Call               = SDLK_CALL,
        EndCall            = SDLK_ENDCALL,
        LeftTab            = SDLK_LEFT_TAB,
        Level5Shift        = SDLK_LEVEL5_SHIFT,
        MultiKeyCompose    = SDLK_MULTI_KEY_COMPOSE,
        LeftMeta           = SDLK_LMETA,
        RightMeta          = SDLK_RMETA,
        LeftHyper          = SDLK_LHYPER,
        RightHyper         = SDLK_RHYPER,
    };

    enum class NT_API MouseButton
    {
        Left   = SDL_BUTTON_LEFT,
        Middle = SDL_BUTTON_MIDDLE,
        Right  = SDL_BUTTON_RIGHT,
        X1     = SDL_BUTTON_X1,
        X2     = SDL_BUTTON_X2,
    };

    enum class NT_API GamepadButton
    {
        South         = SDL_GAMEPAD_BUTTON_SOUTH,
        East          = SDL_GAMEPAD_BUTTON_EAST,
        West          = SDL_GAMEPAD_BUTTON_WEST,
        North         = SDL_GAMEPAD_BUTTON_NORTH,
        Back          = SDL_GAMEPAD_BUTTON_BACK,
        Guide         = SDL_GAMEPAD_BUTTON_GUIDE,
        Start         = SDL_GAMEPAD_BUTTON_START,
        LeftStick     = SDL_GAMEPAD_BUTTON_LEFT_STICK,
        RightStick    = SDL_GAMEPAD_BUTTON_RIGHT_STICK,
        LeftShoulder  = SDL_GAMEPAD_BUTTON_LEFT_SHOULDER,
        RightShoulder = SDL_GAMEPAD_BUTTON_RIGHT_SHOULDER,
        DPadUp        = SDL_GAMEPAD_BUTTON_DPAD_UP,
        DPadDown      = SDL_GAMEPAD_BUTTON_DPAD_DOWN,
        DPadLeft      = SDL_GAMEPAD_BUTTON_DPAD_LEFT,
        DPadRight     = SDL_GAMEPAD_BUTTON_DPAD_RIGHT,
        Misc1         = SDL_GAMEPAD_BUTTON_MISC1,
        RightPaddle1  = SDL_GAMEPAD_BUTTON_RIGHT_PADDLE1,
        LeftPaddle1   = SDL_GAMEPAD_BUTTON_LEFT_PADDLE1,
        RightPaddle2  = SDL_GAMEPAD_BUTTON_RIGHT_PADDLE2,
        LeftPaddle2   = SDL_GAMEPAD_BUTTON_LEFT_PADDLE2,
        Touchpad      = SDL_GAMEPAD_BUTTON_TOUCHPAD,
        Misc2         = SDL_GAMEPAD_BUTTON_MISC2,
        Misc3         = SDL_GAMEPAD_BUTTON_MISC3,
        Misc4         = SDL_GAMEPAD_BUTTON_MISC4,
        Misc5         = SDL_GAMEPAD_BUTTON_MISC5,
        Misc6         = SDL_GAMEPAD_BUTTON_MISC6,
    };
} // namespace Nt

#endif // _CORE_CODES_H_
